### PR TITLE
fix: module hot reload

### LINKED ISSUE #773: Hot reloading a module will not reload the properties if they are added/removed during the development of a module
**Operating system and application version**
 - OS: Any

**Describe the bug**
When developing a module and adding new properties or removing some or changing the attributes of a property, this is not reflected in the property inspector of modV. 

**To Reproduce**
1. Put a custom module into the modules folder
2. Add a property
3. Delete another property
4. Change the attribute of another property
5. See that the module is hot reloaded, but you can't see the changed attribute or change the other attributes anymore

**Expected behavior**
The property inspector is updated accordingly without any errors and I can still change all properties.

### PR DESCRIPTION
**Pull request by 2xAA**
Fixes #773

### CODE REVIEW

**Comment by 2xAA** [comment]
We could replace `JSON.parse(JSON.stringify())` with [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

**Comment by 2xAA** [comment]
Yikes, maybe not!
https://jsbench.me/gql72as3ud/2

**Review by TimPietrusky — APPROVED** [review]
LGTM, tested both with a simple and my heavy presets. Everything looks fine.

**Pull request merged**
