### PR TITLE
feat(texture): Class to render a 2D texture

### LINKED ISSUE #329: Image control is broken
## Issue Description
After a putting an image into the `images` folder in the [media manager](https://modv.js.org/guide/mediaManager.html#location), it's not possible to select the `Images` tab in modV:

screen shot 2019-02-28 at 22 06 25

### PR DESCRIPTION
**Pull request by TimPietrusky**
In order to load different kind of textures (e.g. another layer or an image) into modV and scale it
or change it position, this class can be used.

fix #329

### CODE REVIEW

**Comment by TimPietrusky** [comment]
Would be nice to also have some documentation on how to add an image into the media folder so that this can also be used by someone.

**Comment by TimPietrusky** [comment]
Documentation is ready to review in https://github.com/vcync/modv.vcync.gl/pull/21

**Comment by 2xAA** [comment]
Thanks Tim, this looks great!

The only thing I change would be to use percentage values to position the image rather than fixed values as when resizing the window the image will not retain its expected position.

**Comment by TimPietrusky** [comment]
@2xAA I updated the PR to include what you have asked! Is that what you had in mind?

**Comment by 2xAA** [comment]
@TimPietrusky Yes, exactly.

Why have you set -500 and 500 as the bounds though?

Is it not -100 and 100?

**Comment by TimPietrusky** [comment]
@2xAA you are right, I thought that if you scale it down you need to set a higher offset, but that is not true at all.

**Pull request merged**
