### PR TITLE
feat(expression): adds expressions

### LINKED ISSUE #415: Input Breakpoints to change a property value for different thresholds
**Is your feature request related to a problem? Please describe.**
When using an audio feature for a property, I want to change the value when it reaches a certain threshold, so that only then the audio feature kicks in, not all the time. 

**Describe the solution you'd like**
Configure a list of breakpoints that can force an update to the value, they could also overlap and then the order of the breakpoints (top to bottom or left to right) tells which one is "the main" one. In here I would also love to write down an expression to boost the value above the certain threshold, like then it reaches `value + 20%` it should be `value * 5.0` or `value / 1.2`.

### LINKED ISSUE #453: [Audio Feature]: min / max value
**Is your feature request related to a problem? Please describe.**
I'm frustrated that the min / max that already exists for a module property is not used when attaching an audio feature to that property. 

**Describe the solution you'd like**
Either add another min / max input to the audio feature or use the min / max value also as a range for the property value including the changes from the audio feature. 

**Describe alternatives you've considered**
In modV 2 we could use expressions, but in modV 3 there is no possibility to limit the changes an audio feature has on a property. 

**Additional context**
Party related to #415

### PR DESCRIPTION
**Pull request by 2xAA**
Adds the expression editor from modV 2

fix #453 fix #415

### CODE REVIEW

**Comment by 2xAA** [comment]
Requires preset saving functionality and docs on modv.vcync.gl to be added before merge.

**Comment by 2xAA** [comment]
Expressions docs PR here: https://github.com/vcync/modv.vcync.gl/pull/24

**Comment by TimPietrusky** [comment]
@2xAA I tested it and it works great.

I would prefer if the textarea would be bigger, can I make the changes? I found the code for this, but not sure if you want that or not.

**Comment by 2xAA** [comment]
Sure, implement away 😅

**Comment by 2xAA** [comment]
@TimPietrusky sure! Implement away 😅

**Comment by TimPietrusky** [comment]
@2xAA so if you agree with my change that makes the textarea fill up the whole space in width, we can merge this!

**Comment by TimPietrusky** [comment]
@2xAA also https://github.com/vcync/modv.vcync.gl/pull/24#pullrequestreview-542307538 was merged and we just need to create a new version.

**Comment by 2xAA** [comment]
@TimPietrusky I just reduced the cell size slightly so it's in line with Tween above. You still have double the room.

Thanks for reviewing the docs!

**Pull request merged**
