### PR TITLE
fix(preset-gallery): Fixes reference to originalName in Module's meta

### LINKED ISSUE #331: Preset Gallery wrongly reports invalid Presets as valid
The title

### PR DESCRIPTION
**Pull request by 2xAA**
Fixes #331

### CODE REVIEW

**Comment by TimPietrusky** [comment]
@2xAA It would be nice if it could also show the modules that are missing, otherwise it will be super hard to actually fix the preset. 

I also would appreciate it if I could still load the preset, but have a small warning icon that it is not complete.

**Comment by 2xAA** [comment]
@TimPietrusky Could those be a feature request?

**Comment by TimPietrusky** [comment]
@2xAA the thing with this PR is that if it gets merged, I can't use my presets anymore, because they rely on Shadertoy. So even when I have a lot of modules that are build-in, I still can't use my preset. 

So I would like to have a solution that actually works for both scenarios.

**Comment by 2xAA** [comment]
@TimPietrusky Right, I understand but the scenario you describe actually is a bug right now, not a feature.

Ideally I'd want to separate the two items out as one is a feature and one is a bugfix.

The alternative, to tide you over, is to make Shader modules from the Shadertoy code using the docs as reference to writing Modules and keep local copies of your own Modules - this is what I have for my own Modules which I don't want to put into the main modV repo. This approach is also safer for you in case of no network connection or the author of the Shadertoy shader deletes their shader at any point.

You can prettify the preset JSON to see which Modules you require for now and the listing of missing modules should come as a secondary PR following this one as a feature.

You can run this function in the console when modV is running with an Array of module names to generate an Array of Shader modules which can then be saved to disk.

```JavaScript
function makeShader(names) {
  if (!Array.isArray(names)) {
	return makeShader([names])
  }

  const modules = names.reduce((arr, name) => {
    const module = modVVue.$store.state.modVModules.active[name]

    if (module) {
      const { props, fragmentShader, meta } = module

      arr.push({
        props,
        fragmentShader,
        meta
      })
    }

    return arr
  }, [])

  return modules
}
```

Example usage:
```JavaScript
makeShader(['Dolphin', 'Virtual Dolphins', 'Module name 3'])
  .forEach(module => console.log(JSON.stringify(module)))
```

**Comment by TimPietrusky** [comment]
@2xAA I opened #334 to separate this bug with the feature.

**Review by TimPietrusky — APPROVED** [review]
LGTM

**Pull request merged**
