### PR TITLE
fix(modules): handle non registered modules

### LINKED ISSUE #660: All modules are broken when loaded from a preset that contains a module that doesn't exist anymore
**Operating system and application version**
 - OS: any
 - 3.19.1

**Describe the bug**
When saving a preset with a any custom module, then removing the module and loading the preset, the module is not loaded. Every other module in that preset is also broken then. 

**To Reproduce**
1. Add a few modules to your groups
2. Save the preset
3. Rename one of the module in the filesystem
4. Load the preset
5. See that every module is broken

**Expected behavior**
At least all the other modules are still loaded and the broken module is highlighted somehow, maybe even shows the name of the module that should be loaded, but doesn't exist anymore. This way the user could actually see what is happening. 

**Additional context**
[broken_preset.zip](https://github.com/vcync/modV/files/7575174/broken_preset.zip)

### PR DESCRIPTION
**Pull request by 2xAA**
fixes #660

Screenshot 2021-11-22 at 09 54 25

### CODE REVIEW

**Comment by TimPietrusky** [comment]
I'm very sad, but it's not working :(

But it will work in 2022, FOR SURE!!! 

[20211022_iieinander_react_advanced_london_backup.json.zip](https://github.com/vcync/modV/files/7765090/20211022_iieinander_react_advanced_london_backup.json.zip)

**Comment by 2xAA** [comment]
@TimPietrusky Please try again. I've added some try catch blocks for fs operations.

**Review by TimPietrusky — APPROVED** [review]
LGTM, perfect code! <3

**Pull request merged**
