### PR TITLE
feat(hot-reload): adds hot reloading of active modules

### PR DESCRIPTION
**Pull request by 2xAA**
Custom modules will now be reloaded, preserving module prop state

re #462

### CODE REVIEW

**Comment by 2xAA** [comment]
Writing a 2D Module should be updated to reflect this update
https://modv.vcync.gl/v3/guide/writingA2dModule.html#_1-create-a-new-file

**Review by TimPietrusky — APPROVED** [review]
Looks very clean and perfect 🎉

**Comment by TimPietrusky** [comment]
@2xAA why do we have to update the docs?

**Comment by 2xAA** [comment]
@TimPietrusky This paragraph:

> If your Module is within a Group already, you'll need to remove it from said Group and drag your Module in again from the Gallery to use the updated Module.

This is now no longer true. An active module will use the hot reloaded code without any user intervention.

**Comment by 2xAA** [comment]
PR for docs here:
https://github.com/vcync/modv.vcync.gl/pull/18

**Comment by TimPietrusky** [comment]
@2xAA oh yeah you are super right! Missed that part.

**Pull request merged**
