### PR TITLE
feat(audio): adds audio feature display value to input config

### LINKED ISSUE #380: Audio visualisation "debug" panel
(split from vcync/modv-3#130)

A panel to show what the audio features are doing at any moment would be useful to see what all the features correspond to.

An example of this could be similar to Hedron's FFT band visualisation underneath the preview:
https://github.com/nudibranchrecords/hedron

## Dependencies

vcync/modV#379 as this was part of vcync/modv-3#130.

### PR DESCRIPTION
**Pull request by 2xAA**
Shows what the selected audio feature is doing at any one time

re #380

### CODE REVIEW

**Comment by TimPietrusky** [comment]
Looks super cool and works for `rms`, `zsr` and `energy`. Everything else shows no value at all.

**Comment by TimPietrusky** [comment]
@2xAA can we get this into modV before the workshop? I just want to know as I would then use it in the preparation. 

Edit: I will take a look why this is not working.

**Comment by 2xAA** [comment]
@TimPietrusky We can. Let me know how you get on with this. I have a little time over the weekend to also take a look

**Comment by 2xAA** [comment]
@TimPietrusky Looks like the selected features in the input config audio dropdown aren't added to the meyda store "features" array when selected. A few are already available since Modules request them.

This was an efficiency thing, but I actually don't think this matters much.

We should just request all features from Meyda, it seems fast enough to do this.

**Review by TimPietrusky — APPROVED** [review]
LGTM ⭐️

**Pull request merged**
