### PR TITLE
feat(video): add support for webcodec video

### LINKED ISSUE #521: Video support
**Is your feature request related to a problem? Please describe.**
People are using videos when they compose their visual sets and want to use them in modV. 
People have a music video ready and want to apply some awesome effects in modV to use that for a live gig. 

**Describe the solution you'd like**
Use a component to add a video (e.g. `Texture 2D`) that provides playback methods for the video:
* Play / Pause video
* Change the playback speed
* Start time / end time of the snippet of the video
* Restart video automatically vs play only once
* Loop video

**Describe alternatives you've considered**
See https://github.com/vcync/modV/discussions/501#discussioncomment-197293

### LINKED ISSUE #695: Move webcam stream to worker using VideoFrame from WebCodec API
https://w3c.github.io/webcodecs/samples/webcam-in-worker/
https://codesandbox.io/s/offscreencanvas-webcodec-worker-video-forked-r3w32

### PR DESCRIPTION
**Pull request by 2xAA**
fix #521

To-do:
- [x] Style playback controls
- [x] Fix texture controls (currently duplicates assets in memory when focused)
- [x] Store playback settings on texture

### CODE REVIEW

**Comment by radiodario** [comment]
FXERdL9WQAAHthM-1

**Comment by TimPietrusky** [comment]
@radiodario checking it now!

**Comment by TimPietrusky** [comment]
@2xAA I tested this again and what is not working is to load the video from a preset:

1. Add module `Texture 2D`
2. Select `texture` type `video`
3. Choose a video
4. Save the preset
5. Reload modV
6. Load the preset
7. See that nothing is playing and there is no error in the dev console when the preset is loaded
8. See that you can't use any controls in the module inspector for the video, as there are errors (different for each control that is used):

```
Cannot read properties of undefined (reading 'getElapsedTime')
Cannot read properties of undefined (reading 'playbackrate')
Cannot read properties of undefined (reading 'paused')
Cannot set properties of undefined (setting 'currentTime')
```

@radiodario so sadly we can't merge this yet, but hopefully soon!

**Comment by 2xAA** [comment]
Thanks @TimPietrusky. The latest commit should fix this.

**Pull request merged**
