### PR TITLE
fix: conform path paths for crossplatform compatibility

### PR DESCRIPTION
**Pull request by 2xAA**
Also fixes bad import for uuid in video.js.

### CODE REVIEW

**Comment by TimPietrusky** [comment]
@2xAA for real? The path separator? 🙈 
Super strange that we have never encountered this so far. 

Thanks for the fix!

**Review by TimPietrusky — APPROVED** [review]
LGTM!

**Comment by 2xAA** [comment]
This is just for loading the textures, I don’t think it fixes what we saw
on Thursday.

I haven’t been able to test with my MacBook again yet.

**Comment by TimPietrusky** [comment]
Oh I see, thanks!

**Pull request merged**
