### PR TITLE
feat(auto-update): adds github releases electron-builder config

### PR DESCRIPTION
**Pull request by 2xAA**
Adds required GitHub config options to electron-builder for auto-updater and GitHub releases.

re #371

### CODE REVIEW

**Comment by TimPietrusky** [comment]
@2xAA does this mean that Travis will no longer publish the binaries to GitHub, but electron-builder will do this?

**Review by TimPietrusky — APPROVED** [review]
LGTM

**Comment by 2xAA** [comment]
> @2xAA does this mean that Travis will no longer publish the binaries to GitHub, but electron-builder will do this? 

Upon reading the docs again, yes I think electron-builder does this.

We would remove the Travis publish step.

**Pull request merged**
