### PR TITLE
feat(renderer): adds three.js renderer

### PR DESCRIPTION
**Pull request by 2xAA**
Doesn't use the latest version of three as it has some bugs with CubeCameras, from my recent work with three.js.
We can update later down the road.

### CODE REVIEW

**Comment by TimPietrusky** [comment]
Code looks super clean and is very simple, thank you very much! 

The cube is only showing, when something else is visible in the background. I guess this is a bug?

**Comment by 2xAA** [comment]
@TimPietrusky no, that's intended - I've updated the sample module to include a toggle to use the canvas as material map or not. Previously, if there was nothing on the canvas, the map is entirely transparent so nothing would be output.

**Comment by TimPietrusky** [comment]
Works perfectly, thank you both!

**Pull request merged**
