### PR TITLE
fix(inputs): adds clean-up of inputs when modules or groups are removed

### PR DESCRIPTION
**Pull request by 2xAA**
Cleans up unneeded inputs, which in-turn will create cleaner presets.

Screenshot 2021-11-16 at 15 29 23

### CODE REVIEW

**Comment by TimPietrusky** [comment]
We tested this by deleting a group that contains a module, but the module is not deleted from the preset when the group is deleted!

**Comment by 2xAA** [comment]
@TimPietrusky The new changes fix this behaviour, please test again.

**Review by TimPietrusky — APPROVED** [review]
LGTM, thank you very much!

**Pull request merged**
