### PR TITLE
feat(midi): Support for NoteOn and CC buttons

### LINKED ISSUE #506: [MIDI] CC as NoteOn
**Is your feature request related to a problem? Please describe.**
In order to support MIDI controllers with buttons, we need to have some switch that interprets CC as NoteOn, so that the button behaves like a toggle. 

**Describe the solution you'd like**
In the MIDI controller config, I would like to change every CC to NoteOn. 

**Describe alternatives you've considered**
Not using a MIDI controller.

### PR DESCRIPTION
**Pull request by TimPietrusky**
fix #506

What is still missing is to light up the button and to loading "ccAsNoteOn" from the preset (as right now it's disabled after the preset is loaded.

### CODE REVIEW

**Review by 2xAA — CHANGES_REQUESTED** [review]
Looks good. 

We can work together to figure out why the preset state is not being restored.
I think that's a separate issue however as the new value is being saved into the JSON output.

I have a couple of comments.

The `ccAsNoteOn` key on the device doesn't seem to affect a noteOn message being learned or not in my tests.

"CC as Note On" seems to be suggesting the opposite of what we expect here.
"Note On as CC" is more accurate I think, as we're treating noteOn messages as if it were a CC button.

**Comment by TimPietrusky** [comment]
> The ccAsNoteOn key on the device doesn't seem to affect a noteOn message being learned or not in my tests.

Yeah we are not touching `NoteOn` at all (as those are working fine already). With that option activated, every `CC` message gets transformed into a `NoteOn` so that they behave the same. But I guess this is why this never came into modV 2 as you expect something different here. Would you mind to describe your use case? 

What is also happening in this feature is that a `NoteOff` is not commited into the store as this would deactivate the change triggered by `NoteOn` when someone releases the button. Might this be the thing that doesn't make sense from your point of view? I might also hide this behind a flag (transform momentary into a toggle buttons) if we don't want to make this the default behavior. 

This is needed especially on Novation Launchpad controllers, as the buttons of the main grid are `NoteOn`, but all buttons around the main grid are `CC`. Novation doesn't provide any software to change that behavior.

**Comment by 2xAA** [comment]
@TimPietrusky - thank you for the explanation.

I think we should still rename `ccAsNoteOn` to something like `ccLatch` and also add an option to latch `NoteOn` messages if needed.

This allows anybody to add any controller and customise the setup very easily.

Later we should create a MIDI Mapper which allows complete control over this, however this is a separate issue.

**Comment by TimPietrusky** [comment]
> I think we should still rename ccAsNoteOn to something like ccLatch

Why would you rename this? For me it would be very unclear what `ccLatch` actually means. And as this is only a short term solution, I would rather name it something that explains itself, like `ccAsNoteOn` as this is basically what happens here. 

> also add an option to latch NoteOn messages if needed.

I would name this `disableNoteOff`. 

@2xAA What do you think?

**Comment by 2xAA** [comment]
@TimPietrusky 

From my point of view there are two points.

Firstly, I don't think the end user will understand what noteOn is unless they know MIDI.

Secondly, noteOn from a MIDI instrument infers there will be a following noteOff when the key is released. Usually the key isn't latched but this PR adds this latching mechanism.

We're adding non-standard functionality, so we should reflect this by naming it something different.

Calling it a latch also allows us to use the terminology over CC and noteOn/Off instead of "disable noteOff" we call the same perceived functionality the same thing.

**Comment by TimPietrusky** [comment]
@2xAA ok, I will make the changes.

**Comment by TimPietrusky** [comment]
@2xAA I did all the changes.

For the problem related to loading the settings from a preset I created https://github.com/vcync/modV/issues/523

**Review by 2xAA — APPROVED** [review]

**Comment by 2xAA** [comment]
@TimPietrusky Thanks for the changes, looks good to me :)

**Pull request merged**
